telegram:
  token:
  admins:
    -
    -
  webhook:
    domain:
    path:
  webapp:
    host:
    port:
  miniapp:
    link:
  payment_provider_token:
  notification_chat:

database:
  path:

config:
font: